const cereal_data = [
  {
    name: 'Apple Cinnamon Cheerios',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '2',
    'milligrams of sodium': '180',
    'grams of dietary fiber': '1.5',
    'grams of complex carbohydrates': '10.5',
    'grams of sugars': '10',
    'milligrams of potassium': '70',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '29.509541',
  },
  {
    name: 'Basic 4',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '130',
    'grams of protein': '3',
    'grams of fat': '2',
    'milligrams of sodium': '210',
    'grams of dietary fiber': '2',
    'grams of complex carbohydrates': '18',
    'grams of sugars': '8',
    'milligrams of potassium': '100',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1.33',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '37.038562',
  },
  {
    name: 'Cheerios',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '6',
    'grams of fat': '2',
    'milligrams of sodium': '290',
    'grams of dietary fiber': '2',
    'grams of complex carbohydrates': '17',
    'grams of sugars': '1',
    'milligrams of potassium': '105',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1.25',
    'Rating of cereal': '50.764999',
  },
  {
    name: 'Cinnamon Toast Crunch',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '120',
    'grams of protein': '1',
    'grams of fat': '3',
    'milligrams of sodium': '210',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '13',
    'grams of sugars': '9',
    'milligrams of potassium': '45',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '19.823573',
  },
  {
    name: 'Clusters',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '3',
    'grams of fat': '2',
    'milligrams of sodium': '140',
    'grams of dietary fiber': '2',
    'grams of complex carbohydrates': '13',
    'grams of sugars': '7',
    'milligrams of potassium': '105',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.5',
    'Rating of cereal': '40.400208',
  },
  {
    name: 'Cocoa Puffs',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '1',
    'grams of fat': '1',
    'milligrams of sodium': '180',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '12',
    'grams of sugars': '13',
    'milligrams of potassium': '55',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '22.736446',
  },
  {
    name: 'Count Chocula',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '1',
    'grams of fat': '1',
    'milligrams of sodium': '180',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '12',
    'grams of sugars': '13',
    'milligrams of potassium': '65',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '22.396513',
  },
  {
    name: 'Crispy Wheat & Raisins',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '140',
    'grams of dietary fiber': '2',
    'grams of complex carbohydrates': '11',
    'grams of sugars': '10',
    'milligrams of potassium': '120',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '36.176196',
  },
  {
    name: 'Golden Grahams',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '1',
    'grams of fat': '1',
    'milligrams of sodium': '280',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '15',
    'grams of sugars': '9',
    'milligrams of potassium': '45',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '23.804043',
  },
  {
    name: 'Honey Nut Cheerios',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '3',
    'grams of fat': '1',
    'milligrams of sodium': '250',
    'grams of dietary fiber': '1.5',
    'grams of complex carbohydrates': '11.5',
    'grams of sugars': '10',
    'milligrams of potassium': '90',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '31.072217',
  },
  {
    name: 'Kix',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '260',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '21',
    'grams of sugars': '3',
    'milligrams of potassium': '40',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1.5',
    'Rating of cereal': '39.241114',
  },
  {
    name: 'Lucky Charms',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '180',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '12',
    'grams of sugars': '12',
    'milligrams of potassium': '55',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '26.734515',
  },
  {
    name: 'Multi-Grain Cheerios',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '220',
    'grams of dietary fiber': '2',
    'grams of complex carbohydrates': '15',
    'grams of sugars': '6',
    'milligrams of potassium': '90',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '40.105965',
  },
  {
    name: 'Oatmeal Raisin Crisp',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '130',
    'grams of protein': '3',
    'grams of fat': '2',
    'milligrams of sodium': '170',
    'grams of dietary fiber': '1.5',
    'grams of complex carbohydrates': '13.5',
    'grams of sugars': '10',
    'milligrams of potassium': '120',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1.25',
    'Number of cups in one serving': '0.5',
    'Rating of cereal': '30.450843',
  },
  {
    name: 'Raisin Nut Bran',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '3',
    'grams of fat': '2',
    'milligrams of sodium': '140',
    'grams of dietary fiber': '2.5',
    'grams of complex carbohydrates': '10.5',
    'grams of sugars': '8',
    'milligrams of potassium': '140',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.5',
    'Rating of cereal': '39.7034',
  },
  {
    name: 'Total Corn Flakes',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '200',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '21',
    'grams of sugars': '3',
    'milligrams of potassium': '35',
    'vitamins and minerals (% of FDA recommendation)': '100',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '38.839746',
  },
  {
    name: 'Total Raisin Bran',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '140',
    'grams of protein': '3',
    'grams of fat': '1',
    'milligrams of sodium': '190',
    'grams of dietary fiber': '4',
    'grams of complex carbohydrates': '15',
    'grams of sugars': '14',
    'milligrams of potassium': '230',
    'vitamins and minerals (% of FDA recommendation)': '100',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1.5',
    'Number of cups in one serving': '1',
    'Rating of cereal': '28.592785',
  },
  {
    name: 'Total Whole Grain',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '3',
    'grams of fat': '1',
    'milligrams of sodium': '200',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '16',
    'grams of sugars': '3',
    'milligrams of potassium': '110',
    'vitamins and minerals (% of FDA recommendation)': '100',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '46.658844',
  },
  {
    name: 'Triples',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '250',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '21',
    'grams of sugars': '3',
    'milligrams of potassium': '60',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '39.106174',
  },
  {
    name: 'Trix',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '1',
    'grams of fat': '1',
    'milligrams of sodium': '140',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '13',
    'grams of sugars': '12',
    'milligrams of potassium': '25',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '27.753301',
  },
  {
    name: 'Wheaties',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '3',
    'grams of fat': '1',
    'milligrams of sodium': '200',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '17',
    'grams of sugars': '3',
    'milligrams of potassium': '110',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '51.592193',
  },
  {
    name: 'Wheaties Honey Gold',
    Manufacturer: 'General Mills',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '200',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '16',
    'grams of sugars': '8',
    'milligrams of potassium': '60',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '36.187559',
  },
  {
    name: 'All-Bran',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '70',
    'grams of protein': '4',
    'grams of fat': '1',
    'milligrams of sodium': '260',
    'grams of dietary fiber': '9',
    'grams of complex carbohydrates': '7',
    'grams of sugars': '5',
    'milligrams of potassium': '320',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.33',
    'Rating of cereal': '59.425505',
  },
  {
    name: 'All-Bran with Extra Fiber',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '50',
    'grams of protein': '4',
    'grams of fat': '0',
    'milligrams of sodium': '140',
    'grams of dietary fiber': '14',
    'grams of complex carbohydrates': '8',
    'grams of sugars': '0',
    'milligrams of potassium': '330',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.5',
    'Rating of cereal': '93.704912',
  },
  {
    name: 'Apple Jacks',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '0',
    'milligrams of sodium': '125',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '11',
    'grams of sugars': '14',
    'milligrams of potassium': '30',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '33.174094',
  },
  {
    name: 'Corn Flakes',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '2',
    'grams of fat': '0',
    'milligrams of sodium': '290',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '21',
    'grams of sugars': '2',
    'milligrams of potassium': '35',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '45.863324',
  },
  {
    name: 'Corn Pops',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '1',
    'grams of fat': '0',
    'milligrams of sodium': '90',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '13',
    'grams of sugars': '12',
    'milligrams of potassium': '20',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '35.782791',
  },
  {
    name: "Cracklin' Oat Bran",
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '3',
    'grams of fat': '3',
    'milligrams of sodium': '140',
    'grams of dietary fiber': '4',
    'grams of complex carbohydrates': '10',
    'grams of sugars': '7',
    'milligrams of potassium': '160',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.5',
    'Rating of cereal': '40.448772',
  },
  {
    name: 'Crispix',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '0',
    'milligrams of sodium': '220',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '21',
    'grams of sugars': '3',
    'milligrams of potassium': '30',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '46.895644',
  },
  {
    name: 'Froot Loops',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '125',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '11',
    'grams of sugars': '13',
    'milligrams of potassium': '30',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '32.207582',
  },
  {
    name: 'Frosted Flakes',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '1',
    'grams of fat': '0',
    'milligrams of sodium': '200',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '14',
    'grams of sugars': '11',
    'milligrams of potassium': '25',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '31.435973',
  },
  {
    name: 'Frosted Mini-Wheats',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '3',
    'grams of fat': '0',
    'milligrams of sodium': '0',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '14',
    'grams of sugars': '7',
    'milligrams of potassium': '100',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.8',
    'Rating of cereal': '58.345141',
  },
  {
    name: 'Fruitful Bran',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '120',
    'grams of protein': '3',
    'grams of fat': '0',
    'milligrams of sodium': '240',
    'grams of dietary fiber': '5',
    'grams of complex carbohydrates': '14',
    'grams of sugars': '12',
    'milligrams of potassium': '190',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1.33',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '41.015492',
  },
  {
    name: 'Just Right Crunchy  Nuggets',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '170',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '17',
    'grams of sugars': '6',
    'milligrams of potassium': '60',
    'vitamins and minerals (% of FDA recommendation)': '100',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '36.523683',
  },
  {
    name: 'Just Right Fruit & Nut',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '140',
    'grams of protein': '3',
    'grams of fat': '1',
    'milligrams of sodium': '170',
    'grams of dietary fiber': '2',
    'grams of complex carbohydrates': '20',
    'grams of sugars': '9',
    'milligrams of potassium': '95',
    'vitamins and minerals (% of FDA recommendation)': '100',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1.3',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '36.471512',
  },
  {
    name: 'Mueslix Crispy Blend',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '160',
    'grams of protein': '3',
    'grams of fat': '2',
    'milligrams of sodium': '150',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '17',
    'grams of sugars': '13',
    'milligrams of potassium': '160',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1.5',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '30.313351',
  },
  {
    name: 'Nut&Honey Crunch',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '120',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '190',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '15',
    'grams of sugars': '9',
    'milligrams of potassium': '40',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '29.924285',
  },
  {
    name: 'Nutri-Grain Almond-Raisin',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '140',
    'grams of protein': '3',
    'grams of fat': '2',
    'milligrams of sodium': '220',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '21',
    'grams of sugars': '7',
    'milligrams of potassium': '130',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1.33',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '40.69232',
  },
  {
    name: 'Nutri-grain Wheat',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '90',
    'grams of protein': '3',
    'grams of fat': '0',
    'milligrams of sodium': '170',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '18',
    'grams of sugars': '2',
    'milligrams of potassium': '90',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '59.642837',
  },
  {
    name: 'Product 19',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '3',
    'grams of fat': '0',
    'milligrams of sodium': '320',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '20',
    'grams of sugars': '3',
    'milligrams of potassium': '45',
    'vitamins and minerals (% of FDA recommendation)': '100',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '41.50354',
  },
  {
    name: 'Raisin Bran',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '120',
    'grams of protein': '3',
    'grams of fat': '1',
    'milligrams of sodium': '210',
    'grams of dietary fiber': '5',
    'grams of complex carbohydrates': '14',
    'grams of sugars': '12',
    'milligrams of potassium': '240',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1.33',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '39.259197',
  },
  {
    name: 'Raisin Squares',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '90',
    'grams of protein': '2',
    'grams of fat': '0',
    'milligrams of sodium': '0',
    'grams of dietary fiber': '2',
    'grams of complex carbohydrates': '15',
    'grams of sugars': '6',
    'milligrams of potassium': '110',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.5',
    'Rating of cereal': '55.333142',
  },
  {
    name: 'Rice Krispies',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '0',
    'milligrams of sodium': '290',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '22',
    'grams of sugars': '3',
    'milligrams of potassium': '35',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '40.560159',
  },
  {
    name: 'Smacks',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '70',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '9',
    'grams of sugars': '15',
    'milligrams of potassium': '40',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '31.230054',
  },
  {
    name: 'Special K',
    Manufacturer: 'Kelloggs',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '6',
    'grams of fat': '0',
    'milligrams of sodium': '230',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '16',
    'grams of sugars': '3',
    'milligrams of potassium': '55',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '53.131324',
  },
  {
    name: '100% Bran',
    Manufacturer: 'Nabisco',
    type: 'Cold',
    'calories per serving': '70',
    'grams of protein': '4',
    'grams of fat': '1',
    'milligrams of sodium': '130',
    'grams of dietary fiber': '10',
    'grams of complex carbohydrates': '5',
    'grams of sugars': '6',
    'milligrams of potassium': '280',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.33',
    'Rating of cereal': '68.402973',
  },
  {
    name: 'Shredded Wheat',
    Manufacturer: 'Nabisco',
    type: 'Cold',
    'calories per serving': '80',
    'grams of protein': '2',
    'grams of fat': '0',
    'milligrams of sodium': '0',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '16',
    'grams of sugars': '0',
    'milligrams of potassium': '95',
    'vitamins and minerals (% of FDA recommendation)': '0',
    'Display shelf': '1',
    'Weight in ounces per one serving': '0.83',
    'Number of cups in one serving': '1',
    'Rating of cereal': '68.235885',
  },
  {
    name: "Shredded Wheat 'n'Bran",
    Manufacturer: 'Nabisco',
    type: 'Cold',
    'calories per serving': '90',
    'grams of protein': '3',
    'grams of fat': '0',
    'milligrams of sodium': '0',
    'grams of dietary fiber': '4',
    'grams of complex carbohydrates': '19',
    'grams of sugars': '0',
    'milligrams of potassium': '140',
    'vitamins and minerals (% of FDA recommendation)': '0',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '74.472949',
  },
  {
    name: 'Shredded Wheat spoon size',
    Manufacturer: 'Nabisco',
    type: 'Cold',
    'calories per serving': '90',
    'grams of protein': '3',
    'grams of fat': '0',
    'milligrams of sodium': '0',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '20',
    'grams of sugars': '0',
    'milligrams of potassium': '120',
    'vitamins and minerals (% of FDA recommendation)': '0',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '72.801787',
  },
  {
    name: 'Strawberry Fruit Wheats',
    Manufacturer: 'Nabisco',
    type: 'Cold',
    'calories per serving': '90',
    'grams of protein': '2',
    'grams of fat': '0',
    'milligrams of sodium': '15',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '15',
    'grams of sugars': '5',
    'milligrams of potassium': '90',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '59.363993',
  },
  {
    name: 'Bran Flakes',
    Manufacturer: 'Post',
    type: 'Cold',
    'calories per serving': '90',
    'grams of protein': '3',
    'grams of fat': '0',
    'milligrams of sodium': '210',
    'grams of dietary fiber': '5',
    'grams of complex carbohydrates': '13',
    'grams of sugars': '5',
    'milligrams of potassium': '190',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '53.313813',
  },
  {
    name: 'Fruit & Fibre Dates; Walnuts; and Oats',
    Manufacturer: 'Post',
    type: 'Cold',
    'calories per serving': '120',
    'grams of protein': '3',
    'grams of fat': '2',
    'milligrams of sodium': '160',
    'grams of dietary fiber': '5',
    'grams of complex carbohydrates': '12',
    'grams of sugars': '10',
    'milligrams of potassium': '200',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1.25',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '40.917047',
  },
  {
    name: 'Fruity Pebbles',
    Manufacturer: 'Post',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '1',
    'grams of fat': '1',
    'milligrams of sodium': '135',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '13',
    'grams of sugars': '12',
    'milligrams of potassium': '25',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '28.025765',
  },
  {
    name: 'Golden Crisp',
    Manufacturer: 'Post',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '2',
    'grams of fat': '0',
    'milligrams of sodium': '45',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '11',
    'grams of sugars': '15',
    'milligrams of potassium': '40',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.88',
    'Rating of cereal': '35.252444',
  },
  {
    name: 'Grape Nuts Flakes',
    Manufacturer: 'Post',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '3',
    'grams of fat': '1',
    'milligrams of sodium': '140',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '15',
    'grams of sugars': '5',
    'milligrams of potassium': '85',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.88',
    'Rating of cereal': '52.076897',
  },
  {
    name: 'Grape-Nuts',
    Manufacturer: 'Post',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '3',
    'grams of fat': '0',
    'milligrams of sodium': '170',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '17',
    'grams of sugars': '3',
    'milligrams of potassium': '90',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.25',
    'Rating of cereal': '53.371007',
  },
  {
    name: 'Great Grains Pecan',
    Manufacturer: 'Post',
    type: 'Cold',
    'calories per serving': '120',
    'grams of protein': '3',
    'grams of fat': '3',
    'milligrams of sodium': '75',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '13',
    'grams of sugars': '4',
    'milligrams of potassium': '100',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.33',
    'Rating of cereal': '45.811716',
  },
  {
    name: 'Honey-comb',
    Manufacturer: 'Post',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '1',
    'grams of fat': '0',
    'milligrams of sodium': '180',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '14',
    'grams of sugars': '11',
    'milligrams of potassium': '35',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1.33',
    'Rating of cereal': '28.742414',
  },
  {
    name: 'Post Nat. Raisin Bran',
    Manufacturer: 'Post',
    type: 'Cold',
    'calories per serving': '120',
    'grams of protein': '3',
    'grams of fat': '1',
    'milligrams of sodium': '200',
    'grams of dietary fiber': '6',
    'grams of complex carbohydrates': '11',
    'grams of sugars': '14',
    'milligrams of potassium': '260',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1.33',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '37.840594',
  },
  {
    name: '100% Natural Bran',
    Manufacturer: 'Quaker Oats',
    type: 'Cold',
    'calories per serving': '120',
    'grams of protein': '3',
    'grams of fat': '5',
    'milligrams of sodium': '15',
    'grams of dietary fiber': '2',
    'grams of complex carbohydrates': '8',
    'grams of sugars': '8',
    'milligrams of potassium': '135',
    'vitamins and minerals (% of FDA recommendation)': '0',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '33.983679',
  },
  {
    name: "Cap'n'Crunch",
    Manufacturer: 'Quaker Oats',
    type: 'Cold',
    'calories per serving': '120',
    'grams of protein': '1',
    'grams of fat': '2',
    'milligrams of sodium': '220',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '12',
    'grams of sugars': '12',
    'milligrams of potassium': '35',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '18.042851',
  },
  {
    name: 'Honey Graham Ohs',
    Manufacturer: 'Quaker Oats',
    type: 'Cold',
    'calories per serving': '120',
    'grams of protein': '1',
    'grams of fat': '2',
    'milligrams of sodium': '220',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '12',
    'grams of sugars': '11',
    'milligrams of potassium': '45',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '21.871292',
  },
  {
    name: 'Life',
    Manufacturer: 'Quaker Oats',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '4',
    'grams of fat': '2',
    'milligrams of sodium': '150',
    'grams of dietary fiber': '2',
    'grams of complex carbohydrates': '12',
    'grams of sugars': '6',
    'milligrams of potassium': '95',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '45.328074',
  },
  {
    name: 'Puffed Rice',
    Manufacturer: 'Quaker Oats',
    type: 'Cold',
    'calories per serving': '50',
    'grams of protein': '1',
    'grams of fat': '0',
    'milligrams of sodium': '0',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '13',
    'grams of sugars': '0',
    'milligrams of potassium': '15',
    'vitamins and minerals (% of FDA recommendation)': '0',
    'Display shelf': '3',
    'Weight in ounces per one serving': '0.5',
    'Number of cups in one serving': '1',
    'Rating of cereal': '60.756112',
  },
  {
    name: 'Puffed Wheat',
    Manufacturer: 'Quaker Oats',
    type: 'Cold',
    'calories per serving': '50',
    'grams of protein': '2',
    'grams of fat': '0',
    'milligrams of sodium': '0',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '10',
    'grams of sugars': '0',
    'milligrams of potassium': '50',
    'vitamins and minerals (% of FDA recommendation)': '0',
    'Display shelf': '3',
    'Weight in ounces per one serving': '0.5',
    'Number of cups in one serving': '1',
    'Rating of cereal': '63.005645',
  },
  {
    name: 'Quaker Oat Squares',
    Manufacturer: 'Quaker Oats',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '4',
    'grams of fat': '1',
    'milligrams of sodium': '135',
    'grams of dietary fiber': '2',
    'grams of complex carbohydrates': '14',
    'grams of sugars': '6',
    'milligrams of potassium': '110',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.5',
    'Rating of cereal': '49.511874',
  },
  {
    name: 'Almond Delight',
    Manufacturer: 'Ralston Purina',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '2',
    'milligrams of sodium': '200',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '14',
    'grams of sugars': '8',
    'milligrams of potassium': '-1',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '34.384843',
  },
  {
    name: 'Bran Chex',
    Manufacturer: 'Ralston Purina',
    type: 'Cold',
    'calories per serving': '90',
    'grams of protein': '2',
    'grams of fat': '1',
    'milligrams of sodium': '200',
    'grams of dietary fiber': '4',
    'grams of complex carbohydrates': '15',
    'grams of sugars': '6',
    'milligrams of potassium': '125',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '49.120253',
  },
  {
    name: 'Corn Chex',
    Manufacturer: 'Ralston Purina',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '2',
    'grams of fat': '0',
    'milligrams of sodium': '280',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '22',
    'grams of sugars': '3',
    'milligrams of potassium': '25',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '41.445019',
  },
  {
    name: 'Double Chex',
    Manufacturer: 'Ralston Purina',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '2',
    'grams of fat': '0',
    'milligrams of sodium': '190',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '18',
    'grams of sugars': '5',
    'milligrams of potassium': '80',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.75',
    'Rating of cereal': '44.330856',
  },
  {
    name: 'Muesli Raisins; Dates; & Almonds',
    Manufacturer: 'Ralston Purina',
    type: 'Cold',
    'calories per serving': '150',
    'grams of protein': '4',
    'grams of fat': '3',
    'milligrams of sodium': '95',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '16',
    'grams of sugars': '11',
    'milligrams of potassium': '170',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '37.136863',
  },
  {
    name: 'Muesli Raisins; Peaches; & Pecans',
    Manufacturer: 'Ralston Purina',
    type: 'Cold',
    'calories per serving': '150',
    'grams of protein': '4',
    'grams of fat': '3',
    'milligrams of sodium': '150',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '16',
    'grams of sugars': '11',
    'milligrams of potassium': '170',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '3',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '34.139765',
  },
  {
    name: 'Rice Chex',
    Manufacturer: 'Ralston Purina',
    type: 'Cold',
    'calories per serving': '110',
    'grams of protein': '1',
    'grams of fat': '0',
    'milligrams of sodium': '240',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '23',
    'grams of sugars': '2',
    'milligrams of potassium': '30',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1.13',
    'Rating of cereal': '41.998933',
  },
  {
    name: 'Wheat Chex',
    Manufacturer: 'Ralston Purina',
    type: 'Cold',
    'calories per serving': '100',
    'grams of protein': '3',
    'grams of fat': '1',
    'milligrams of sodium': '230',
    'grams of dietary fiber': '3',
    'grams of complex carbohydrates': '17',
    'grams of sugars': '3',
    'milligrams of potassium': '115',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '49.787445',
  },
  {
    name: 'Maypo',
    Manufacturer: 'American Home Food Products',
    type: 'Hot',
    'calories per serving': '100',
    'grams of protein': '4',
    'grams of fat': '1',
    'milligrams of sodium': '0',
    'grams of dietary fiber': '0',
    'grams of complex carbohydrates': '16',
    'grams of sugars': '3',
    'milligrams of potassium': '95',
    'vitamins and minerals (% of FDA recommendation)': '25',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '54.850917',
  },
  {
    name: 'Cream of Wheat (Quick)',
    Manufacturer: 'Nabisco',
    type: 'Hot',
    'calories per serving': '100',
    'grams of protein': '3',
    'grams of fat': '0',
    'milligrams of sodium': '80',
    'grams of dietary fiber': '1',
    'grams of complex carbohydrates': '21',
    'grams of sugars': '0',
    'milligrams of potassium': '-1',
    'vitamins and minerals (% of FDA recommendation)': '0',
    'Display shelf': '2',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '1',
    'Rating of cereal': '64.533816',
  },
  {
    name: 'Quaker Oatmeal',
    Manufacturer: 'Quaker Oats',
    type: 'Hot',
    'calories per serving': '100',
    'grams of protein': '5',
    'grams of fat': '2',
    'milligrams of sodium': '0',
    'grams of dietary fiber': '2.7',
    'grams of complex carbohydrates': '-1',
    'grams of sugars': '-1',
    'milligrams of potassium': '110',
    'vitamins and minerals (% of FDA recommendation)': '0',
    'Display shelf': '1',
    'Weight in ounces per one serving': '1',
    'Number of cups in one serving': '0.67',
    'Rating of cereal': '50.828392',
  },
];

let wrapper = d3.select('#wrapper').selectAll('.cereal').data(cereal_data);
// .enter()
// .append('div')
// .text((d) => `${d.name}: ${d['Rating of cereal']}`)
// .attr('class', 'bar')
// .style('width', (d) => {
//   return d['Rating of cereal'] * 10 + 'px';
// });

let entering = wrapper.enter().append('div').classed('cereal', true);

entering
  .append('div')
  .classed('label', true)
  .text((d) => d.name)
  .on('mouseover', (d, i) => {
    toggleClass(i + 1, true);
  })
  .on('mouseout', (d, i) => {
    toggleClass(i + 1, false);
  });

entering
  .append('div')
  .classed('bar', true)
  .text((d) => `${Math.round(d['Rating of cereal'])}`)
  .style('width', (d) => {
    return d['Rating of cereal'] * 5 + 'px';
  })
  .on('mouseover', (d, i) => {
    toggleClass(i + 1, true);
  })
  .on('mouseout', (d, i) => {
    toggleClass(i + 1, false);
  });

function sort() {
  d3.selectAll('.cereal').sort(
    (a, b) => b['Rating of cereal'] - a['Rating of cereal']
  );
}

function toggleClass(i, toggle) {
  d3.select(`#wrapper div:nth-child(${i}) .bar`).classed(
    'highlightBar',
    toggle
  );
  d3.select(`#wrapper div:nth-child(${i}) .label`).classed(
    'highlightLabel',
    toggle
  );
}
